### PR TITLE
Add GL2 support

### PR DESCRIPTION
**Pull request by nek0**
I took the liberty to create also GL2 compatibility.

### CODE REVIEW

**Comment by cocreature** [comment]
Thanks! I’ve squashed the commits and merged this manually.

**Comment by nek0** [comment]
can you push this also to master and hackage? thanks.

**Comment by cocreature** [comment]
I’ll try to find the time to make a release next week.

**Comment by cocreature** [comment]
I’ve released `nanovg-0.6.0.0`.

**Pull request closed without merging**
